import React, { useState, useEffect } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { MapPin, CreditCard, Wallet, ArrowLeft, CheckCircle2 } from 'lucide-react';
import { useCart } from '../context/CartContext';
import { useAuth } from '../context/AuthContext';
import api from '../api/axios';
import './Payment.css';

// Hook to dynamically load external scripts
const useRazorpayScript = () => {
  const [isLoaded, setIsLoaded] = useState(false);

  useEffect(() => {
    const script = document.createElement('script');
    script.src = 'https://checkout.razorpay.com/v1/checkout.js';
    script.async = true;
    script.onload = () => setIsLoaded(true);
    document.body.appendChild(script);

    return () => {
      document.body.removeChild(script);
    };
  }, []);

  return isLoaded;
};

const Payment = () => {
  const { cart, discount, clearCart } = useCart();
  const { user } = useAuth();
  const navigate = useNavigate();
  const [selectedAddress, setSelectedAddress] = useState('home');
  const [customAddress, setCustomAddress] = useState('');
  const [selectedPayment, setSelectedPayment] = useState('razorpay');
  const [isProcessing, setIsProcessing] = useState(false);
  const isRazorpayLoaded = useRazorpayScript();

  const deliveryFee = cart.total > 0 ? 3.99 : 0;
  const taxes = cart.total * 0.08;
  const discountAmount = cart.total * discount;
  const finalTotal = cart.total - discountAmount + deliveryFee + taxes;

  const handlePayment = async () => {
    setIsProcessing(true);
    
    try {
      const CUSTOMER_ID = user?.id || 1;

      // 1. First clear any existing backend cart for this customer
      try {
        await api.delete(`/cart/clear/${CUSTOMER_ID}`);
      } catch(e) {}

      // 2. Add all local cart items to backend cart
      for (const item of cart.items) {
        await api.post('/cart/add', {
          customerId: CUSTOMER_ID,
          menuItemId: item.id,
          quantity: item.quantity,
          customization: ''
        });
      }

      // 3. Determine the actual address string
      let deliveryAddressStr = "FRONTEND_FALLBACK";
      if (selectedAddress === 'home') {
        deliveryAddressStr = "123 Main Street, Apt 4B, New York, NY 10001";
      } else if (selectedAddress === 'work') {
        deliveryAddressStr = "456 Business Blvd, Floor 12, New York, NY 10002";
      } else if (selectedAddress === 'custom' && customAddress) {
        deliveryAddressStr = customAddress;
      }

      // 4. Place Order via OrderService
      const paymentMode = selectedPayment.toUpperCase();
      const orderResponse = await api.post(`/orders/place/${CUSTOMER_ID}?paymentMode=${paymentMode}&deliveryAddress=${encodeURIComponent(deliveryAddressStr)}`, {
        deliveryAddress: deliveryAddressStr
      });
      const orderData = orderResponse.data;
      
      // 4. Handle Payment Gateway or COD
      if (paymentMode === 'RAZORPAY') {
        // Fetch Payment details generated by OrderService internally
        const paymentRes = await api.get(`/payment/order/${orderData.orderId}`);
        const paymentInfo = paymentRes.data;

        // Since we don't have a real Razorpay key, we mock the Razorpay flow
        setTimeout(async () => {
          try {
            // Verify payment on backend with mock payment ID
            await api.post(`/payment/verify?razorpayOrderId=${paymentInfo.razorpayOrderId}&razorpayPaymentId=pay_mock_${Date.now()}`);
            
            clearCart();
            navigate(`/track/${orderData.orderId}`);
          } catch (err) {
            console.error("Payment verification failed", err);
            alert("Payment verification failed. Please contact support.");
            setIsProcessing(false);
          }
        }, 1500);

      } else {
        // COD or other modes
        clearCart();
        navigate(`/track/${orderData.orderId}`);
      }
      
    } catch (error) {
      console.error('Checkout failed', error);
      alert('Failed to place order. Please try again.');
      setIsProcessing(false);
    }
  };


  if (cart.items.length === 0 && !isProcessing) {
    return (
      <div className="payment-page">
        <div className="container" style={{ textAlign: 'center', paddingTop: '100px' }}>
          <h2>Nothing to pay for!</h2>
          <p>Your cart is empty.</p>
          <Link to="/restaurants" className="btn-primary" style={{ marginTop: '1rem', display: 'inline-block' }}>
            Go to Restaurants
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="payment-page">
      <div className="container">
        <div className="payment-header">
          <Link to="/cart" className="back-link">
            <ArrowLeft size={20} /> Back to Cart
          </Link>
          <h1>Checkout</h1>
        </div>

        <div className="checkout-layout">
          <div className="checkout-details-section">
            {/* Address Selection */}
            <motion.div 
              className="glass-card section-card"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
            >
              <div className="section-title">
                <MapPin size={24} className="text-primary" />
                <h2>Delivery Address</h2>
              </div>
              
              <div className="options-grid">
                <div 
                  className={`option-card ${selectedAddress === 'home' ? 'selected' : ''}`}
                  onClick={() => setSelectedAddress('home')}
                >
                  <div className="radio-btn"></div>
                  <div className="option-info">
                    <h4>Home</h4>
                    <p>123 Main Street, Apt 4B, New York, NY 10001</p>
                  </div>
                </div>
                
                <div 
                  className={`option-card ${selectedAddress === 'work' ? 'selected' : ''}`}
                  onClick={() => setSelectedAddress('work')}
                >
                  <div className="radio-btn"></div>
                  <div className="option-info">
                    <h4>Work</h4>
                    <p>456 Business Blvd, Floor 12, New York, NY 10002</p>
                  </div>
                </div>
                
                {customAddress && (
                  <div 
                    className={`option-card ${selectedAddress === 'custom' ? 'selected' : ''}`}
                    onClick={() => setSelectedAddress('custom')}
                  >
                    <div className="radio-btn"></div>
                    <div className="option-info">
                      <h4>Custom Address</h4>
                      <p>{customAddress}</p>
                    </div>
                  </div>
                )}
                
                <div 
                  className="add-new-address" 
                  onClick={() => {
                    const addr = prompt("Enter your new delivery address:");
                    if (addr && addr.trim() !== '') {
                      setCustomAddress(addr);
                      setSelectedAddress('custom');
                    }
                  }}
                  style={{ cursor: 'pointer' }}
                >
                  + Add New Address
                </div>
              </div>
            </motion.div>

            {/* Payment Method */}
            <motion.div 
              className="glass-card section-card"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 }}
            >
              <div className="section-title">
                <Wallet size={24} className="text-primary" />
                <h2>Payment Method</h2>
              </div>
              
              <div className="payment-options">
                <div 
                  className={`payment-option ${selectedPayment === 'razorpay' ? 'selected' : ''}`}
                  onClick={() => setSelectedPayment('razorpay')}
                >
                  <div className="radio-btn"></div>
                  <div className="payment-info">
                    <img src="https://upload.wikimedia.org/wikipedia/commons/8/89/Razorpay_logo.svg" alt="Razorpay" className="payment-logo" />
                    <span>Pay via UPI, Cards, NetBanking</span>
                  </div>
                </div>
                
                <div 
                  className={`payment-option ${selectedPayment === 'card' ? 'selected' : ''}`}
                  onClick={() => setSelectedPayment('card')}
                >
                  <div className="radio-btn"></div>
                  <div className="payment-info">
                    <CreditCard size={24} className="text-muted" />
                    <span>Credit / Debit Card</span>
                  </div>
                </div>
                
                <div 
                  className={`payment-option ${selectedPayment === 'cod' ? 'selected' : ''}`}
                  onClick={() => setSelectedPayment('cod')}
                >
                  <div className="radio-btn"></div>
                  <div className="payment-info">
                    <div className="cash-icon">💵</div>
                    <span>Cash on Delivery</span>
                  </div>
                </div>
              </div>
            </motion.div>
          </div>

          {/* Order Summary */}
          <motion.div 
            className="checkout-summary-section"
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.2 }}
          >
            <div className="glass-card summary-card">
              <h3>Order Summary</h3>
              
              <div className="summary-items-small">
                {cart.items.map(item => (
                  <div key={item.id} className="small-item">
                    <span>{item.quantity}x {item.name}</span>
                    <span>₹{(item.price * item.quantity).toFixed(2)}</span>
                  </div>
                ))}
              </div>
              
              <div className="bill-divider"></div>
              
              <div className="bill-breakdown">
                <div className="bill-row">
                  <span>Item Total</span>
                  <span>₹{cart.total.toFixed(2)}</span>
                </div>
                {discount > 0 && (
                  <div className="bill-row" style={{ color: 'var(--primary)' }}>
                    <span>Discount</span>
                    <span>-₹{discountAmount.toFixed(2)}</span>
                  </div>
                )}
                <div className="bill-row">
                  <span>Delivery Fee</span>
                  <span>₹{deliveryFee.toFixed(2)}</span>
                </div>
                <div className="bill-row">
                  <span>Taxes</span>
                  <span>₹{taxes.toFixed(2)}</span>
                </div>
                
                <div className="bill-divider"></div>
                
                <div className="bill-row bill-total">
                  <span>Total Amount</span>
                  <span>₹{finalTotal.toFixed(2)}</span>
                </div>
              </div>

              <button 
                className={`btn-primary pay-btn ${isProcessing ? 'processing' : ''}`}
                onClick={handlePayment}
                disabled={isProcessing}
              >
                {isProcessing ? (
                  <span className="loader-dots">Processing</span>
                ) : (
                  <>
                    <span>Pay ₹{finalTotal.toFixed(2)}</span>
                    <CheckCircle2 size={20} />
                  </>
                )}
              </button>
              
              <div className="secure-badge">
                <CreditCard size={14} />
                <span>100% Secure Payment</span>
              </div>
            </div>
          </motion.div>
        </div>
      </div>
    </div>
  );
};

export default Payment;
